"""The audio extension's mapping editor as static files, for the Audio guide.

    python firmware/toolchain/editor_demo.py           # write web/public/guide/audio-editor/
    python firmware/toolchain/editor_demo.py --check   # is what is there current?

The guide at /guide/audio shows the extension's real editor - the page the
popup's "Open editor" opens, not a screenshot - in a window on the page, and
what it maps drives the 3D board beside it (web/src/components/guide/
EditorWindow.tsx is the other end). This writes what that window loads:

    index.html          tools/patternflow-audio-extension/editor.html, with one
                        tag added: bridge.js, between the adapter and the editor
    editor.css          )
    mapping.js          )  the extension's files, byte for byte (line ends
    editor-adapter.js   )  apart)
    editor.js           )
    bridge.js           BRIDGE_JS below: the guide's end of the editor

Nothing of the extension is rewritten. A page that is not an extension has no
chrome.storage, so editor-adapter.js runs its own demo source (a synthesized
spectrum; the bar says "demo source"), and bridge.js stands between that
adapter and the editor - its header comment says what it does and why. The
extension's folder is not touched: this only reads it.

Rerun it after any change to those four files, to editor.html or to BRIDGE_JS;
`--check` exits 1 when the folder is stale. The folder is this script's alone:
it is emptied and rewritten each run.

bridge.js maps levels to knobs the way the capture does (offscreen.js tick()),
with PFMap's own functions, but the few lines that join them are written
again there. CHAIN below is those lines as offscreen.js has them: if one is
gone the capture's chain has changed, this script stops, and BRIDGE_JS is to
be brought back in step before the list is.
"""

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, "..", ".."))
EXT = os.path.join(REPO, "tools", "patternflow-audio-extension")
OUT = os.path.join(REPO, "web", "public", "guide", "audio-editor")

# Copied as they are.
VERBATIM = ["editor.css", "mapping.js", "editor-adapter.js", "editor.js"]

# The one edit to editor.html.
ADAPTER_TAG = '<script src="editor-adapter.js"></script>'
BRIDGE_TAG = '<script src="bridge.js"></script>'

# What bridge.js follows, as offscreen.js writes it (see the docstring).
CHAIN = [
    "const TICK_MS = 33;",
    "const REPORT_MS = 120;",
    "const a = raw > levels[i] ? config.attack : config.smoothing;",
    "levels[i] = a * raw + (1 - a) * levels[i];",
    "if (auto) PFMap.trackEnvelope(envelopes[i], levels[i]);",
    "const pos = PFMap.position(levels[i], bands[i], auto ? envelopes[i] : null);",
    "const output = PFMap.output(bands[i], pos);",
    "if (!bands[i].muted) lanes[bands[i].knob] = output;",
    "if (running) config = PFMap.normalizeConfig(message.config, PFMap.SOURCE);",
]
# And the two things it leans on in the demo adapter.
ADAPTER = [
    "onFrame(fn) { frameFn = fn; demoFrame(); setInterval(demoFrame, 120); }",
    "e && e.hi - e.lo > PFMap.ENV_MIN_SPAN + 1e-6 ? e : null);",
]


def read(name):
    with open(os.path.join(EXT, name), encoding="utf-8", newline="") as f:
        return f.read().replace("\r\n", "\n")


def render():
    """{file name: bytes} - everything the folder should hold."""
    for name, lines in (("offscreen.js", CHAIN), ("editor-adapter.js", ADAPTER)):
        text = read(name)
        for line in lines:
            if line not in text:
                raise SystemExit(
                    "%s no longer has the line\n    %s\nbridge.js (BRIDGE_JS in "
                    "editor_demo.py) follows it: bring the bridge in step, then "
                    "this list." % (name, line))
    html = read("editor.html")
    if html.count(ADAPTER_TAG) != 1:
        raise SystemExit("editor.html: expected one %s" % ADAPTER_TAG)
    html = html.replace(ADAPTER_TAG, ADAPTER_TAG + "\n" + BRIDGE_TAG)
    head = "<!doctype html>\n"
    if not html.startswith(head):
        raise SystemExit("editor.html: does not start with its doctype")
    html = (head + "<!-- GENERATED by firmware/toolchain/editor_demo.py from "
            "tools/patternflow-audio-extension/editor.html. Do not edit. -->\n"
            + html[len(head):])
    files = {"index.html": html, "bridge.js": BRIDGE_JS}
    for name in VERBATIM:
        files[name] = read(name)
    return {n: t.encode("utf-8") for n, t in files.items()}


def main():
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass
    ap = argparse.ArgumentParser(description="Write the Audio guide's editor demo.")
    ap.add_argument("--check", action="store_true", help="exit 1 if the folder is stale")
    args = ap.parse_args()
    files = render()
    total = sum(len(b) for b in files.values())
    if args.check:
        have = set(os.listdir(OUT)) if os.path.isdir(OUT) else set()
        # A Windows checkout has the folder's files with CRLF line ends; what
        # is written here, and what git stores, has LF.
        def on_disk(n):
            with open(os.path.join(OUT, n), "rb") as f:
                return f.read().replace(b"\r\n", b"\n")
        stale = sorted(n for n, b in files.items() if n not in have or on_disk(n) != b)
        stale += sorted(have - set(files))
        if stale:
            print("editor demo is stale: %s\nrun: python firmware/toolchain/editor_demo.py"
                  % ", ".join(stale))
            sys.exit(1)
        print("editor demo current (%d files, %d bytes)" % (len(files), total))
        return
    os.makedirs(OUT, exist_ok=True)
    for n in os.listdir(OUT):
        p = os.path.join(OUT, n)
        if os.path.isfile(p):
            os.remove(p)
    for n, b in sorted(files.items()):
        with open(os.path.join(OUT, n), "wb") as f:
            f.write(b)
    print("wrote %d files, %d bytes -> %s" % (len(files), total, os.path.relpath(OUT, REPO)))
    for n, b in sorted(files.items()):
        print("  %-18s %7d" % (n, len(b)))


# ── the guide's end of the editor ──────────────────────────────────────────

BRIDGE_JS = r'''/* Patternflow Audio guide: between the editor and its demo source.
 * GENERATED by firmware/toolchain/editor_demo.py -- edit BRIDGE_JS there, rerun.
 *
 * Loaded after editor-adapter.js and before editor.js. Outside the extension
 * the adapter is its demo: a synthesized spectrum, the mapping in memory, and
 * each band's output straight off its level. That is a preview of the editor.
 * The guide shows the editor driving a board, so five things are added here,
 * around window.PFAdapter and without a change to any of the extension's
 * files:
 *
 *   the capture's chain    The knob values are worked out as the capture works
 *                          them out (offscreen.js tick()): every 33 ms, the
 *                          level glided by Attack and Damping, auto range's
 *                          envelope at its real rate, PFMap.position and
 *                          PFMap.output, and a muted band sends nothing. The
 *                          editor is handed these values too, so its cursor
 *                          and readout are what the board was told.
 *   to the board           {type:'pf-audio', outputs:[v|null x4]} to the page
 *                          that holds this frame, each tick: v is 0..1 as the
 *                          extension's a= message carries it, null is a lane
 *                          left alone (its '-').
 *   one mapping per tab    The mapping is kept in sessionStorage, so the
 *                          miniature in the card and the window lifted from
 *                          it are one editor: an edit in either is the other's
 *                          at once (the storage event), and survives a reload.
 *   Esc                    {type:'pf-audio', action:'escape'} when Esc is
 *                          pressed and the editor's Preview is not what it
 *                          closes.
 *   its scroll its own     A wheel or a finger that runs past the editor's end
 *                          stops there. Without this the page that holds the
 *                          frame scrolls on, and the guide's step changes
 *                          under the window.
 *
 * The source stays the adapter's: its spectrum, its levels per band, its
 * "demo source" chip. Nothing leaves this folder.
 */
(function () {
  'use strict';

  var source = window.PFAdapter;
  if (!source || typeof PFMap === 'undefined') return;

  var KEY = 'pf-audio-editor:mapping';
  var TICK_MS = 33;       // offscreen.js TICK_MS
  var REPORT_MS = 120;    // offscreen.js REPORT_MS
  var CAPS = source.caps();

  var host = window.parent !== window ? window.parent : null;
  function tell(message) {
    message.type = 'pf-audio';
    if (host) host.postMessage(message, window.location.origin);
  }

  // ── the mapping ─────────────────────────────────────────────────────────

  function stored() {
    try {
      var text = window.sessionStorage.getItem(KEY);
      var raw = text ? JSON.parse(text) : null;
      return raw && Array.isArray(raw.bands) ? raw : null;
    } catch (e) {
      return null;
    }
  }
  function keep(config) {
    try { window.sessionStorage.setItem(KEY, JSON.stringify(config)); } catch (e) { /* private mode */ }
  }
  // A copy made whole, as the capture takes one out of a 'config' message.
  function whole(raw) {
    return PFMap.normalizeConfig(raw ? JSON.parse(JSON.stringify(raw)) : null, CAPS);
  }

  var config = whole(stored());   // what is being mapped with
  var configFn = null;

  // The mapping changed somewhere else (the other frame of this tab).
  function adopt(raw) {
    if (!raw) return;
    config = whole(raw);
    source.saveConfig(whole(raw));   // the demo source listens where the boxes are
    if (configFn) configFn(raw);
  }
  window.addEventListener('storage', function (e) {
    if (e.key === KEY && e.storageArea === window.sessionStorage) adopt(stored());
  });

  // ── the chain (offscreen.js tick()) ─────────────────────────────────────

  var levels = [0, 0, 0, 0];
  var envelopes = [0, 1, 2, 3].map(PFMap.newEnvelope);
  var peakLevels = [-1, -1, -1, -1];
  var peakPos = [0, 0, 0, 0];
  var peakOutputs = [0, 0, 0, 0];
  var heard = null;       // the demo source's last frame
  var frameFn = null;
  var lastReport = 0;

  // editor-adapter.js learned(): an envelope at its minimum span is not one.
  function learned(e) {
    return e.hi - e.lo > PFMap.ENV_MIN_SPAN + 1e-6 ? { lo: e.lo, hi: e.hi } : null;
  }

  function tick() {
    if (!heard || !heard.levels || heard.levels.length < 4) return;
    var bands = config.bands;
    var auto = config.autoRange;
    var i;

    for (i = 0; i < 4; i++) {
      var raw = PFMap.clamp01(heard.levels[i]);
      var a = raw > levels[i] ? config.attack : config.smoothing;
      levels[i] = a * raw + (1 - a) * levels[i];
      if (auto) PFMap.trackEnvelope(envelopes[i], levels[i]);
    }

    var lanes = [null, null, null, null];
    for (i = 0; i < 4; i++) {
      var pos = PFMap.position(levels[i], bands[i], auto ? envelopes[i] : null);
      var output = PFMap.output(bands[i], pos);
      if (!bands[i].muted) lanes[bands[i].knob] = output;
      if (levels[i] > peakLevels[i]) {
        peakLevels[i] = levels[i];
        peakPos[i] = pos;
        peakOutputs[i] = output;
      }
    }
    tell({ outputs: lanes });

    var now = performance.now();
    if (frameFn && now - lastReport > REPORT_MS) {
      lastReport = now;
      frameFn({
        running: true, connected: false, demo: true,
        levels: peakLevels.slice(),
        pos: peakPos.slice(),
        outputs: peakOutputs.slice(),
        spectrum: heard.spectrum,
        env: auto ? envelopes.map(learned) : [],
        autoRange: auto
      });
      peakLevels = [-1, -1, -1, -1];
    }
  }

  // ── the adapter the editor talks to ─────────────────────────────────────

  window.PFAdapter = {
    caps: function () { return CAPS; },
    // What this tab has stored, or nothing (a first run), as the extension's
    // own adapter answers from chrome.storage.
    loadConfig: function () {
      var raw = stored();
      if (raw) source.saveConfig(whole(raw));
      return Promise.resolve(raw);
    },
    saveConfig: function (next) {
      keep(next);
      config = whole(next);
      return source.saveConfig(next);
    },
    resetBand: function (index, current) {
      return source.resetBand(index, current).then(function (next) {
        keep(next);
        config = whole(next);
        return next;
      });
    },
    onConfig: function (fn) { configFn = fn; },
    onFrame: function (fn) {
      frameFn = fn;
      source.onFrame(function (state) { heard = state; });
      tick();
      setInterval(tick, TICK_MS);
    }
  };

  document.addEventListener('keydown', function (e) {
    if (e.key !== 'Escape') return;
    var preview = document.getElementById('pv');
    if (preview && !preview.hidden) return;   // the editor closes its Preview
    tell({ action: 'escape' });
  });

  // This page scrolls at its root; what is left of a scroll at its end is
  // not handed on to the page that holds the frame.
  document.documentElement.style.overscrollBehavior = 'contain';
})();
'''


if __name__ == "__main__":
    main()
